# Generated by Django 4.1.6 on 2023-02-17 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('text', models.TextField(max_length=3000, verbose_name='Text')),
                ('status', models.CharField(choices=[('new', 'New'), ('in progress', 'In Progress'), ('done', 'Done')], default='new', max_length=15, verbose_name='Status')),
                ('deadline', models.DateField(null=True, verbose_name='Deadline')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Creation date and time')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated date and time')),
            ],
        ),
    ]
